# Generated by Django 4.2.7 on 2025-12-15 17:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_procedimento', models.CharField(max_length=100, unique=True, verbose_name='Número do Procedimento/Inquérito')),
                ('local_crime', models.TextField(verbose_name='Local do Crime')),
                ('data_coleta', models.DateTimeField(verbose_name='Data e Hora da Coleta no Local')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Matrícula deve conter apenas letras e números', regex='^[A-Za-z0-9]+$')], verbose_name='Matrícula/Registro')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo/Função')),
                ('delegacia', models.CharField(blank=True, max_length=255, verbose_name='Delegacia/Unidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Policial',
                'verbose_name_plural': 'Policiais',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Custodia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número do Documento')),
                ('hash_pasta', models.CharField(max_length=64, unique=True, verbose_name='Hash SHA-256 da Pasta')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('caminho_pasta', models.TextField(verbose_name='Caminho Completo da Pasta')),
                ('tamanho_total', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho Total (bytes)')),
                ('total_arquivos', models.IntegerField(default=0, verbose_name='Total de Arquivos')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('pdf_gerado', models.BooleanField(default=False, verbose_name='PDF Gerado')),
                ('caminho_pdf', models.TextField(blank=True, verbose_name='Caminho do PDF')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='custodia.caso', verbose_name='Caso')),
                ('policial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodias', to='custodia.policial', verbose_name='Policial Responsável')),
            ],
            options={
                'verbose_name': 'Custódia',
                'verbose_name_plural': 'Custódias',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('caminho_completo', models.TextField(verbose_name='Caminho Completo')),
                ('caminho_relativo', models.TextField(verbose_name='Caminho Relativo')),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('data_modificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Modificação')),
                ('hash_arquivo', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256 do Arquivo')),
                ('tipo_mime', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('duracao_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('custodia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='custodia.custodia', verbose_name='Custódia')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['caminho_relativo'],
            },
        ),
    ]
