# Generated by Django 6.0.4 on 2026-04-16 17:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_custodia_versoes(apps, schema_editor):
    """Ordena custódias por caso, numera versões e encadeia custodia_anterior."""
    Custodia = apps.get_model('custodia', 'Custodia')
    Caso = apps.get_model('custodia', 'Caso')

    for caso in Caso.objects.all():
        custodias = list(
            Custodia.objects.filter(caso_id=caso.id).order_by('data_criacao', 'id')
        )
        if not custodias:
            continue
        total = len(custodias)
        prev_id = None
        for i, c in enumerate(custodias, start=1):
            Custodia.objects.filter(pk=c.pk).update(
                versao=i,
                custodia_anterior_id=prev_id,
                ativo=(i == total),
            )
            prev_id = c.pk


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0002_alter_arquivo_id_alter_caso_id_alter_custodia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodia',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Somente a versão mais recente do caso fica marcada como atual.', verbose_name='Versão atual do caso'),
        ),
        migrations.AddField(
            model_name='custodia',
            name='custodia_anterior',
            field=models.ForeignKey(blank=True, help_text='Versão imediatamente anterior no mesmo caso, se houver.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodias_posteriores', to='custodia.custodia', verbose_name='Custódia anterior'),
        ),
        migrations.AddField(
            model_name='custodia',
            name='versao',
            field=models.PositiveIntegerField(default=1, help_text='Número sequencial da custódia dentro do mesmo procedimento/caso.', verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='custodia',
            name='hash_pasta',
            field=models.CharField(help_text='Hash consolidado desta versão. Pode repetir entre versões/casos distintos.', max_length=64, verbose_name='Hash SHA-256 da Pasta'),
        ),
        migrations.AddIndex(
            model_name='custodia',
            index=models.Index(fields=['caso', 'ativo'], name='custodia_caso_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='custodia',
            index=models.Index(fields=['caso', 'versao'], name='custodia_caso_versao_idx'),
        ),
        migrations.RunPython(backfill_custodia_versoes, noop_reverse),
    ]
