# Generated by Django 6.0.4 on 2026-04-16 17:09

from django.db import migrations, models


def backfill_hash_cadeia_campos(apps, schema_editor):
    Custodia = apps.get_model('custodia', 'Custodia')
    for c in Custodia.objects.all().iterator():
        novos = c.hash_pasta
        anterior_hex = ''
        if c.custodia_anterior_id:
            try:
                prev = Custodia.objects.get(pk=c.custodia_anterior_id)
                anterior_hex = prev.hash_pasta or ''
            except Custodia.DoesNotExist:
                anterior_hex = ''
        Custodia.objects.filter(pk=c.pk).update(
            hash_conteudo_novos=novos,
            hash_cadeia_anterior=anterior_hex,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0003_custodia_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='novo_ou_alterado',
            field=models.BooleanField(default=True, help_text='Falso se o arquivo já existia com o mesmo hash na versão anterior.', verbose_name='Novo ou alterado nesta versão'),
        ),
        migrations.AddField(
            model_name='custodia',
            name='hash_cadeia_anterior',
            field=models.CharField(blank=True, help_text='Cópia do hash final da custódia imediatamente anterior, para rastreabilidade.', max_length=64, verbose_name='Hash final da versão anterior (referência explícita)'),
        ),
        migrations.AddField(
            model_name='custodia',
            name='hash_conteudo_novos',
            field=models.CharField(blank=True, help_text='Agregado SHA-256 apenas dos arquivos novos ou com conteúdo alterado em relação à versão anterior.', max_length=64, null=True, verbose_name='Hash agregado (novos ou alterados nesta versão)'),
        ),
        migrations.AlterField(
            model_name='custodia',
            name='hash_pasta',
            field=models.CharField(help_text='Versão 1: igual ao agregado de todos os arquivos. Versões seguintes: SHA-256 do par (hash da versão anterior | hash agregado só dos arquivos novos ou alterados).', max_length=64, verbose_name='Hash final da cadeia (esta versão)'),
        ),
        migrations.RunPython(backfill_hash_cadeia_campos, noop_reverse),
        migrations.AlterField(
            model_name='custodia',
            name='hash_conteudo_novos',
            field=models.CharField(help_text='Agregado SHA-256 apenas dos arquivos novos ou com conteúdo alterado em relação à versão anterior.', max_length=64, verbose_name='Hash agregado (novos ou alterados nesta versão)'),
        ),
    ]
